FROM node:22

WORKDIR /app

# RUN npm install -g @vue/cli-service-global
# RUN npm install -g @vue/cli-service

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000

HEALTHCHECK --interval=15s --timeout=1s --retries=5 CMD curl -f http://localhost:3000 || exit 1

ENV PATH /usr/local/bin:$PATH

CMD ["npm", "run", "serve"]
