stages:
  # - provision
  - deploy

variables:
  ANSIBLE_HOST_KEY_CHECKING: "False"

# provision:
#   stage: provision
#   script:
#     - echo "$SSH_PRIVATE_KEY" > id_rsa.base64
#     - echo "$SSH_PRIVATE_KEY" | base64 -d > id_rsa
#     - chmod 600 id_rsa
#     - ansible all -i hosts.ini --private-key id_rsa -m ping
#     - ansible-playbook -K -i hosts.ini --private-key id_rsa provision-server.yml --extra-vars "ansible_become_password=$ROOT_PASSWORD"
#   only:
#     - master

deploy:production:
  stage: deploy
  environment:
    name: prod
  script:
    - echo "$SSH_PRIVATE_KEY" | base64 -d > id_rsa
    - chmod 600 id_rsa
    - |
      ansible-playbook -i hosts.ini --private-key id_rsa deploy-application.yml \
        -e "ansible_become_password=$ROOT_PASSWORD" \
        -e "django_db_password=$DJANGO_DB_PASSWORD" \
        -e "django_secret_key=$DJANGO_SECRET_KEY" \
        -e "postgres_password=$POSTGRES_PASSWORD"
  only:
    - master
  needs:
    - provision
