stages:
  - backup
  - provision
  - build
  - deploy

variables:
  ANSIBLE_HOST_KEY_CHECKING: "False"

backup:master:
  stage: backup
  script:
    - echo "Creating backup of master branch..."
    - echo "Debug info: CI_API_V4_URL=$CI_API_V4_URL, CI_PROJECT_ID=$CI_PROJECT_ID"
    - |
      # Create backup using GitLab API (requires CI_JOB_TOKEN)
      BACKUP_TAG="backup-$(date +%Y%m%d-%H%M%S)"
      COMMIT_SHA=$(git rev-parse HEAD)
      
      echo "Creating backup tag: $BACKUP_TAG for commit: $COMMIT_SHA"
      
      # Create tag using GitLab API with verbose output
      TAG_RESPONSE=$(curl -w "\nHTTP_CODE:%{http_code}\n" -s --request POST \
        --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
        --header "Content-Type: application/json" \
        --data "{\"tag_name\": \"$BACKUP_TAG\", \"ref\": \"$COMMIT_SHA\", \"message\": \"Automated backup before deployment\"}" \
        "$CI_API_V4_URL/projects/$CI_PROJECT_ID/repository/tags")
      
      echo "Tag creation response: $TAG_RESPONSE"
      
      if echo "$TAG_RESPONSE" | grep -q "HTTP_CODE:201\|HTTP_CODE:200"; then
        echo "Backup tag created successfully: $BACKUP_TAG"
      else
        echo "Warning: Tag creation may have failed"
      fi
    - |
      # Also create a backup branch using GitLab API
      BACKUP_BRANCH="backup/master-$(date +%Y%m%d-%H%M%S)"
      
      echo "Creating backup branch: $BACKUP_BRANCH for commit: $COMMIT_SHA"
      
      # Create branch using GitLab API with verbose output
      BRANCH_RESPONSE=$(curl -w "\nHTTP_CODE:%{http_code}\n" -s --request POST \
        --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
        --header "Content-Type: application/json" \
        --data "{\"branch\": \"$BACKUP_BRANCH\", \"ref\": \"$COMMIT_SHA\"}" \
        "$CI_API_V4_URL/projects/$CI_PROJECT_ID/repository/branches")
      
      echo "Branch creation response: $BRANCH_RESPONSE"
      
      if echo "$BRANCH_RESPONSE" | grep -q "HTTP_CODE:201\|HTTP_CODE:200"; then
        echo "Backup branch created successfully: $BACKUP_BRANCH"
      else
        echo "Warning: Branch creation may have failed"
        # Try alternative approach - create branch from current HEAD
        echo "Attempting alternative branch creation method..."
        ALT_RESPONSE=$(curl -w "\nHTTP_CODE:%{http_code}\n" -s --request POST \
          --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
          --header "Content-Type: application/json" \
          --data "{\"branch\": \"$BACKUP_BRANCH\", \"ref\": \"master\"}" \
          "$CI_API_V4_URL/projects/$CI_PROJECT_ID/repository/branches")
        echo "Alternative branch creation response: $ALT_RESPONSE"
      fi
  only:
    - master
  when: always

provision:
  stage: provision
  script:
    - echo "$SSH_PRIVATE_KEY" > id_rsa.base64
    - echo "$SSH_PRIVATE_KEY" | base64 -d > id_rsa
    - chmod 600 id_rsa
    - ansible all -i hosts.ini --private-key id_rsa -m ping
    - ansible-playbook -K -i hosts.ini --private-key id_rsa provision-server.yml --extra-vars "ansible_become_password=$ROOT_PASSWORD"
  only:
    - master

build:production:
  stage: build
  before_script:
    - echo "$GITLAB_REGISTRY_PASSWORD" | docker login gitlab.icarostangent.lab:5050 -u $GITLAB_REGISTRY_USERNAME --password-stdin
  script:
    - docker compose -f docker-compose.build.yml pull
    - docker compose -f docker-compose.build.yml build
    - docker compose -f docker-compose.build.yml push
    - docker system prune -f
  only:
    - master
  tags:
    - docker

deploy:production:
  stage: deploy
  environment:
    name: prod
  script:
    - echo "$SSH_PRIVATE_KEY" | base64 -d > id_rsa
    - chmod 600 id_rsa
    - |
      ansible-playbook -i hosts.ini --private-key id_rsa deploy-application.yml \
        -e "ansible_become_password=$ROOT_PASSWORD" \
        -e "django_db_password=$DJANGO_DB_PASSWORD" \
        -e "django_secret_key=$DJANGO_SECRET_KEY" \
        -e "postgres_password=$POSTGRES_PASSWORD" \
        -e "fauxdan_ssh_private_key=$FAUXDAN_SSH_PRIVATE_KEY" \
        -e "fauxdan_ssh_public_key=$FAUXDAN_SSH_PUBLIC_KEY" \
        -e "gitlab_registry_username=$GITLAB_REGISTRY_USERNAME" \
        -e "gitlab_registry_password=$GITLAB_REGISTRY_PASSWORD"
  only:
    - master
  needs:
    - provision
    - build:production
