stages:
  - provision
  - deploy

variables:
  ANSIBLE_HOST_KEY_CHECKING: "False"

provision:
  stage: provision
  script:
    # Write SSH key and inventory to files
    - echo "$SSH_PRIVATE_KEY" | base64 -d > id_rsa && chmod 600 id_rsa
    - echo "$ANSIBLE_INVENTORY" > inventory

    # cat contents of id_rsa
    - cat id_rsa

    # Ping the host to verify connectivity
    - ansible all -i inventory --private-key id_rsa -m ping
    
    # Run the provision playbook
    - ansible-playbook -i inventory --private-key id_rsa provision-server.yml
  only:
    - master

# deploy:staging:
#   stage: deploy
#   environment:
#     name: staging
#     url: https://staging.fauxdan.io
#   script:
#     - echo "$SSH_PRIVATE_KEY" > id_rsa && chmod 600 id_rsa
#     - echo "$ANSIBLE_INVENTORY" > inventory
#     - ansible-playbook -i inventory --private-key id_rsa deploy-application.yml \
#         -e "environment=staging" \
#         -e "git_branch=develop" \
#         -e "gitlab_project=josh/fauxdan" \
#         -e "gitlab_token=$GITLAB_TOKEN"
#   only:
#     - develop
#   when: manual

deploy:
  stage: deploy
  environment:
    name: prod
  script:
    - echo "$SSH_PRIVATE_KEY" > id_rsa && chmod 600 id_rsa
    - echo "$ANSIBLE_INVENTORY" > inventory
    - ansible-playbook -i inventory --private-key id_rsa deploy-application.yml \
        -e "environment=prod" \
        -e "git_branch=master" \
        -e "ansible_become_password=$ANSIBLE_BECOME_PASSWORD"
  only:
    - master
  when: manual
  needs:
    - provision
