stages:
  - provision
  - build
  - deploy

variables:
  ANSIBLE_HOST_KEY_CHECKING: "False"

provision:
  stage: provision
  script:
    - echo "$SSH_PRIVATE_KEY" > id_rsa.base64
    - echo "$SSH_PRIVATE_KEY" | base64 -d > id_rsa
    - chmod 600 id_rsa
    - ansible all -i hosts.ini --private-key id_rsa -m ping
    - ansible-playbook -K -i hosts.ini --private-key id_rsa provision-server.yml --extra-vars "ansible_become_password=$ROOT_PASSWORD"
  only:
    - master

build:production:
  stage: build
  before_script:
    - echo "$GITLAB_REGISTRY_PASSWORD" | docker login gitlab.icarostangent.lab:5050 -u $GITLAB_REGISTRY_USERNAME --password-stdin
  script:
    - docker compose -f docker-compose.build.yml build
    - docker compose -f docker-compose.build.yml push
    - docker system prune -f
  only:
    - master
  tags:
    - docker

deploy:production:
  stage: deploy
  environment:
    name: prod
  script:
    - echo "$SSH_PRIVATE_KEY" | base64 -d > id_rsa
    - chmod 600 id_rsa
    - |
      ansible-playbook -i hosts.ini --private-key id_rsa deploy-application.yml \
        -e "ansible_become_password=$ROOT_PASSWORD" \
        -e "django_db_password=$DJANGO_DB_PASSWORD" \
        -e "django_secret_key=$DJANGO_SECRET_KEY" \
        -e "postgres_password=$POSTGRES_PASSWORD" \
        -e "fauxdan_ssh_private_key=$FAUXDAN_SSH_PRIVATE_KEY" \
        -e "fauxdan_ssh_public_key=$FAUXDAN_SSH_PUBLIC_KEY" \
        -e "gitlab_registry_username=$GITLAB_REGISTRY_USERNAME" \
        -e "gitlab_registry_password=$GITLAB_REGISTRY_PASSWORD"
  only:
    - master
  needs:
    - provision
    - build:production
