---
- name: Provision Server
  hosts: all
  become: yes
  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages
      apt:
        upgrade: dist
        
    - name: Install required system packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - software-properties-common
        state: present

    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
      args:
        creates: /etc/apt/keyrings/docker.asc

    - name: Set read permissions for Docker GPG key
      file:
        path: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker repository
      shell: |
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
          $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
          sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      args:
        creates: /etc/apt/sources.list.d/docker.list

    - name: Update apt cache after adding Docker repository
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
          - docker-buildx-plugin
        state: present

    # Docker Post-installation
    - name: Create docker group
      group:
        name: docker
        state: present

    - name: Add user to docker group
      user:
        name: josh
        groups: docker
        append: yes

    - name: Create Docker certs directory
      file:
        path: /etc/docker/certs.d/gitlab.icarostangent.lab:5050
        state: directory
        mode: '0755'
      become: yes

    - name: Download GitLab certificate
      shell: |
        echo -n | openssl s_client -connect gitlab.icarostangent.lab:5050 -servername gitlab.icarostangent.lab | \
        sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > /etc/docker/certs.d/gitlab.icarostangent.lab:5050/ca.crt
      become: yes

    # Ensure services are running
    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    # Verify installations
    - name: Verify Docker installation
      command: docker --version
      register: docker_version
      changed_when: false

    - name: Verify Docker Compose installation
      command: docker compose version
      register: compose_version
      changed_when: false

    - name: Display versions
      debug:
        msg: 
          - "Docker version: {{ docker_version.stdout }}"
          - "Docker Compose version: {{ compose_version.stdout }}"

    # GitLab Certificate Configuration
 