services:
  backend:
    image: gitlab.icarostangent.lab:5050/josh/fauxdan/backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile.prod.backend
      
  scanner:
    image: gitlab.icarostangent.lab:5050/josh/fauxdan/scanner:latest
    build:
      context: ./backend
      dockerfile: Dockerfile.prod.scanner

  db:
    image: gitlab.icarostangent.lab:5050/josh/fauxdan/db:latest
    build:
      context: ./db
      dockerfile: Dockerfile

  redis:
    image: gitlab.icarostangent.lab:5050/josh/fauxdan/redis:latest
    build:
      context: ./redis
      dockerfile: Dockerfile

  caddy: 
    image: gitlab.icarostangent.lab:5050/josh/fauxdan/caddy:latest
    build:
      context: ./
      dockerfile: ./caddy/Dockerfile
      args:
        VUE_APP_API_URL: https://staging.fauxdan.io

  caddy-admin:
    image: gitlab.icarostangent.lab:5050/josh/fauxdan/caddy-admin:latest
    build:
      context: ./
      dockerfile: ./caddy/Dockerfile
      args:
        VUE_APP_API_URL: https://staging.fauxdan.icarostangent.lab

  tor:
    image: dperson/torproxy
  # Monitoring services (using official images - no custom builds needed)
  prometheus:
    image: prom/prometheus:latest

  grafana:
    image: grafana/grafana:latest

  node-exporter:
    image: prom/node-exporter:latest

  redis-exporter:
    image: oliver006/redis_exporter:latest

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest

  # ELK Stack (using official images - no custom builds needed)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0

  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.0

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0

  log-forwarder:
    image: gitlab.icarostangent.lab:5050/josh/fauxdan/log-forwarder:latest
    build:
      context: ./monitoring
      dockerfile: Dockerfile.log-forwarder
