services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    expose:
      - "3000"
    volumes:
      - ./frontend:/app 
      - node_modules:/app/node_modules
    environment:
      - VUE_APP_API_URL=${VUE_APP_API_URL}
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev.backend
    expose:
      - "8000"
    volumes:
      - ./backend:/app 
      - ./static:/static
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DB_NAME=${DJANGO_DB_NAME}
      - DJANGO_DB_USER=${DJANGO_DB_USER}
      - DJANGO_DB_PASSWORD=${DJANGO_DB_PASSWORD}
      - DJANGO_DB_HOST=${DJANGO_DB_HOST}
      - DJANGO_DB_PORT=${DJANGO_DB_PORT}
    depends_on:
      - db
      - redis
    command: ["/bin/bash", "/app/init.sh"]
    restart: unless-stopped
      
  scanner:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev.scanner
    volumes:
      - ./backend:/app 
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DB_NAME=${DJANGO_DB_NAME}
      - DJANGO_DB_USER=${DJANGO_DB_USER}
      - DJANGO_DB_PASSWORD=${DJANGO_DB_PASSWORD}
      - DJANGO_DB_HOST=${DJANGO_DB_HOST}
    depends_on:
      - db
      - redis
    restart: unless-stopped
    cap_add:
      - NET_ADMIN

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DJANGO_DB_NAME=${DJANGO_DB_NAME}
      - DJANGO_DB_USER=${DJANGO_DB_USER}
      - DJANGO_DB_PASSWORD=${DJANGO_DB_PASSWORD}
      - DJANGO_DB_HOST=${DJANGO_DB_HOST}
    volumes:
      - db_data:/var/lib/postgresql/data
      # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    restart: unless-stopped

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  caddy:  
    build:
      context: ./caddy
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile.dev:/etc/caddy/Caddyfile
      - ./caddy/certs:/etc/caddy/certs
      - ./caddy/data:/data
    restart: unless-stopped

  tor:
    build:
      context: ./tor
    expose:
      - "9050"
      - "9090"
    restart: unless-stopped

volumes:
  db_data:
  redis_data:
  node_modules:
  nginx_logs: