services:
  backend:
    image: gitlab.icarostangent.lab:5050/josh/fauxdan/backend
    build:
      context: ./backend
      dockerfile: Dockerfile.prod.backend
      
  scanner:
    image: gitlab.icarostangent.lab:5050/josh/fauxdan/scanner
    build:
      context: ./backend
      dockerfile: Dockerfile.prod.scanner

  caddy: 
    image: gitlab.icarostangent.lab:5050/josh/fauxdan/caddy
    build:
      context: ./
      dockerfile: ./caddy/Dockerfile
      args:
        VUE_APP_API_URL: __RUNTIME_API_URL__

  tor:
    image: gitlab.icarostangent.lab:5050/josh/fauxdan/tor
    build:
      context: ./tor
      dockerfile: Dockerfile
