services:
  backend:
    image: gitlab.icarostangent.lab:5050/josh/fauxdan/backend
    restart: unless-stopped
    volumes:
      - static:/static

  scanner:
    image: gitlab.icarostangent.lab:5050/josh/fauxdan/scanner
    restart: unless-stopped

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

  nginx:
    image: gitlab.icarostangent.lab:5050/josh/fauxdan/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static:/static
      - nginx_logs:/var/log/nginx
      - letsencrypt:/etc/letsencrypt
      - certbot_webroot:/var/www/certbot
    environment:
      - LETSENCRYPT_EMAIL=icarostangent@gmail.com
    depends_on:
      - backend
    restart: unless-stopped

  tor:
    image: gitlab.icarostangent.lab:5050/josh/fauxdan/tor
    restart: unless-stopped
  
volumes:
  static:
  redis_data:
  nginx_logs:
  letsencrypt:
  certbot_webroot:
