# This is the docker-compose file for the admin interface.
# It is used to run the admin interface in development mode.
# It is not used in production, but used with production environment variables.
# Connects to live database.

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev.backend
    restart: unless-stopped
    volumes:
      - staticfiles:/app/staticfiles
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DB_NAME=${DJANGO_DB_NAME}
      - DJANGO_DB_USER=${DJANGO_DB_USER}
      - DJANGO_DB_PASSWORD=${DJANGO_DB_PASSWORD}
      - DJANGO_DB_HOST=${DJANGO_DB_HOST}
      - DJANGO_DB_PORT=${DJANGO_DB_PORT}
      - DJANGO_ALLOWED_HOSTS=fauxdan.io,localhost,127.0.0.1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - VUE_APP_API_URL=${VUE_APP_API_URL}
    volumes:
      - caddy_data:/data
      - caddy_logs:/var/log/caddy
      - staticfiles:/staticfiles
    depends_on:
      backend:
        condition: service_healthy
  
volumes:
  staticfiles:
  caddy_data:
  caddy_logs: