services:
  backend:
    image: gitlab.icarostangent.lab:5050/josh/fauxdan/backend
    restart: unless-stopped
    volumes:
      - static:/static
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DB_NAME=${DJANGO_DB_NAME}
      - DJANGO_DB_USER=${DJANGO_DB_USER}
      - DJANGO_DB_PASSWORD=${DJANGO_DB_PASSWORD}
      - DJANGO_DB_HOST=${DJANGO_DB_HOST}
      - DJANGO_DB_PORT=${DJANGO_DB_PORT}

  scanner:
    image: gitlab.icarostangent.lab:5050/josh/fauxdan/scanner
    restart: unless-stopped
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DB_NAME=${DJANGO_DB_NAME}
      - DJANGO_DB_USER=${DJANGO_DB_USER}
      - DJANGO_DB_PASSWORD=${DJANGO_DB_PASSWORD}
      - DJANGO_DB_HOST=${DJANGO_DB_HOST}
      - DJANGO_DB_PORT=${DJANGO_DB_PORT}

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

  caddy:
    image: gitlab.icarostangent.lab:5050/josh/fauxdan/caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - VUE_APP_API_URL=${VUE_APP_API_URL}
    volumes:
      - caddy_data:/data
      - caddy_logs:/var/log/caddy

  tor:
    image: gitlab.icarostangent.lab:5050/josh/fauxdan/tor
    restart: unless-stopped
  
volumes:
  static:
  redis_data:
  caddy_data:
  caddy_logs: