services:
  scanner:
    image: gitlab.icarostangent.lab:5050/josh/fauxdan/scanner
    command: ["python3", "manage.py", "run_scanner_service", "--max-concurrent", "5", "--job-types", "masscan,banner_grab,ssl_cert,domain_enum"]
    restart: unless-stopped
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DB_NAME=${DJANGO_DB_NAME}
      - DJANGO_DB_USER=${DJANGO_DB_USER}
      - DJANGO_DB_PASSWORD=${DJANGO_DB_PASSWORD}
      - DJANGO_DB_HOST=${DJANGO_DB_HOST}
      - DJANGO_DB_PORT=${DJANGO_DB_PORT}