services:
  backend:
    image: gitlab.icarostangent.lab:5050/josh/fauxdan/backend
    restart: unless-stopped
    volumes:
      - staticfiles:/app/staticfiles
    environment:
      - DJANGO_DEBUG=False
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DB_NAME=${DJANGO_DB_NAME}
      - DJANGO_DB_USER=${DJANGO_DB_USER}
      - DJANGO_DB_PASSWORD=${DJANGO_DB_PASSWORD}
      - DJANGO_DB_HOST=${DJANGO_DB_HOST}
      - DJANGO_DB_PORT=${DJANGO_DB_PORT}
      - DJANGO_ALLOWED_HOSTS=fauxdan.io,localhost,127.0.0.1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 120s  # This is key - gives Django 2 minutes to start

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

  caddy:
    image: gitlab.icarostangent.lab:5050/josh/fauxdan/caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - VUE_APP_API_URL=${VUE_APP_API_URL}
    volumes:
      - caddy_data:/data
      - caddy_logs:/var/log/caddy
      - staticfiles:/staticfiles
    depends_on:
      backend:
        condition: service_healthy

  tor:
    image: gitlab.icarostangent.lab:5050/josh/fauxdan/tor
    restart: unless-stopped
  
volumes:
  staticfiles:
  redis_data:
  caddy_data:
  caddy_logs: