services:
  frontend:
    image: gitlab.icarostangent.lab:5050/josh/fauxdan/frontend
    restart: unless-stopped

  backend:
    image: gitlab.icarostangent.lab:5050/josh/fauxdan/backend
    restart: unless-stopped
    volumes:
      - static:/static

  scanner:
    image: gitlab.icarostangent.lab:5050/josh/fauxdan/scanner
    restart: unless-stopped

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

  caddy:
    image: gitlab.icarostangent.lab:5050/josh/fauxdan/caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static:/static
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

  tor:
    image: gitlab.icarostangent.lab:5050/josh/fauxdan/tor
    restart: unless-stopped
  
  db:
    image: postgres:16
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    restart: unless-stopped

volumes:
  db_data:
  static:
  redis_data:
  caddy_data:
  caddy_config:
