# Generated by Django 5.1.1 on 2025-08-26 17:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField()),
                ('first_visit', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_visit', models.DateTimeField(auto_now=True)),
                ('total_visits', models.IntegerField(default=1)),
                ('is_bot', models.BooleanField(default=False)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ip_address'], name='analytics_v_ip_addr_d10bd1_idx'), models.Index(fields=['first_visit'], name='analytics_v_first_v_2a312f_idx'), models.Index(fields=['is_bot'], name='analytics_v_is_bot_7ba56b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet')], max_length=20)),
                ('browser', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='analytics.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_on_page', models.DurationField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='analytics.session')),
            ],
            options={
                'indexes': [models.Index(fields=['url'], name='analytics_p_url_b57c0b_idx'), models.Index(fields=['timestamp'], name='analytics_p_timesta_835321_idx')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, max_length=200, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.session')),
            ],
            options={
                'indexes': [models.Index(fields=['event_type'], name='analytics_e_event_t_acfd0a_idx'), models.Index(fields=['category'], name='analytics_e_categor_003499_idx'), models.Index(fields=['timestamp'], name='analytics_e_timesta_fdc538_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['session_id'], name='analytics_s_session_189e16_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['start_time'], name='analytics_s_start_t_05c893_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user'], name='analytics_s_user_id_397035_idx'),
        ),
    ]
