# Generated by Django 5.1.1 on 2025-08-29 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStory',
            fields=[
            ],
            options={
                'verbose_name': 'User Story',
                'verbose_name_plural': 'User Stories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('analytics.session',),
        ),
    ]
