# Generated by Django 5.1.1 on 2025-08-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='visitor',
            unique_together={('ip_address', 'user_agent')},
        ),
    ]
