# Generated by Django 5.1.1 on 2025-08-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_visitor_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='visitor',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='event',
            name='page_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
