# Generated by Django 5.1.1 on 2025-08-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_visitor_unique_together_event_page_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='page_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='referrer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
