# Generated by Django 5.1.1 on 2025-05-05 02:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=255)),
                ('port_number', models.IntegerField()),
                ('proxy_type', models.CharField(choices=[('S4', 'socks4'), ('S5', 'socks5'), ('HP', 'HTTP'), ('HS', 'HTTPS')], max_length=2)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('dead', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255, unique=True)),
                ('private', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('public_host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_hosts', to='internet.host')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(blank=True, max_length=20, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='internet.host')),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_number', models.IntegerField()),
                ('proto', models.CharField(max_length=3)),
                ('status', models.CharField(max_length=25)),
                ('banner', models.TextField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='internet.host')),
            ],
        ),
        migrations.CreateModel(
            name='DNSRelay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='internet.port')),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('scan_command', models.TextField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=25)),
                ('scan_type', models.CharField(default='', max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='port',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='internet.scan'),
        ),
        migrations.AddField(
            model_name='host',
            name='scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='internet.scan'),
        ),
        migrations.CreateModel(
            name='SSLCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=255, unique=True)),
                ('pem_data', models.TextField()),
                ('subject_cn', models.CharField(blank=True, max_length=255, null=True)),
                ('issuer_cn', models.CharField(blank=True, max_length=255, null=True)),
                ('valid_from', models.CharField(max_length=255)),
                ('valid_until', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssl_certificates', to='internet.host')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssl_certificates', to='internet.port')),
            ],
        ),
    ]
