# Generated by Django 5.1.1 on 2025-09-07 23:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('max_concurrent_jobs', models.PositiveIntegerField(default=5)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher number = higher priority')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JobWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('idle', 'Idle'), ('busy', 'Busy'), ('offline', 'Offline'), ('error', 'Error')], default='idle', max_length=20)),
                ('hostname', models.CharField(max_length=255)),
                ('pid', models.PositiveIntegerField(blank=True, null=True)),
                ('supported_job_types', models.JSONField(default=list, help_text='List of supported job types')),
                ('max_concurrent_jobs', models.PositiveIntegerField(default=1)),
                ('current_job_count', models.PositiveIntegerField(default=0)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-last_heartbeat'],
                'indexes': [models.Index(fields=['status'], name='internet_jo_status_ae0df7_idx'), models.Index(fields=['last_heartbeat'], name='internet_jo_last_he_6ff58d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScannerJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('job_type', models.CharField(choices=[('masscan', 'Masscan'), ('nmap', 'Nmap'), ('custom', 'Custom')], default='masscan', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher number = higher priority')),
                ('target', models.CharField(help_text='Target IP, range, or hostname', max_length=500)),
                ('ports', models.JSONField(blank=True, default=list, help_text='List of ports to scan')),
                ('scan_options', models.JSONField(blank=True, default=dict, help_text='Additional scan options')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='When to start the job', null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('error_message', models.TextField(blank=True)),
                ('progress', models.PositiveIntegerField(default=0, help_text='Progress percentage (0-100)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional job metadata')),
                ('assigned_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='internet.jobworker')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='internet.jobqueue')),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanner_jobs', to='internet.scan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scanner_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
                'indexes': [models.Index(fields=['status'], name='internet_sc_status_927729_idx'), models.Index(fields=['job_type'], name='internet_sc_job_typ_8565b5_idx'), models.Index(fields=['queue', 'status'], name='internet_sc_queue_i_aa4c29_idx'), models.Index(fields=['scheduled_for'], name='internet_sc_schedul_d8c6ce_idx'), models.Index(fields=['assigned_worker'], name='internet_sc_assigne_e76b77_idx')],
            },
        ),
    ]
