# Generated by Django 5.1.1 on 2025-08-04 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='port',
            unique_together={('host', 'port_number', 'proto')},
        ),
    ]
