# Generated by Django 5.1.1 on 2025-09-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0002_jobqueue_jobworker_scannerjob'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='port',
            index=models.Index(fields=['banner'], name='internet_po_banner_634ca1_idx'),
        ),
    ]
