# Generated by Django 5.1.1 on 2025-08-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0002_alter_port_unique_together'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['host'], name='internet_do_host_id_2a5b69_idx'),
        ),
        migrations.AddIndex(
            model_name='port',
            index=models.Index(fields=['host'], name='internet_po_host_id_dfb6e4_idx'),
        ),
        migrations.AddIndex(
            model_name='port',
            index=models.Index(fields=['port_number', 'proto'], name='internet_po_port_nu_0a01ab_idx'),
        ),
        migrations.AddIndex(
            model_name='sslcertificate',
            index=models.Index(fields=['host'], name='internet_ss_host_id_ecea36_idx'),
        ),
    ]
