# Generated by Django 5.1.1 on 2025-08-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0003_domain_internet_do_host_id_2a5b69_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='port',
            name='internet_po_port_nu_0a01ab_idx',
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['name'], name='internet_do_name_2fc06f_idx'),
        ),
        migrations.AddIndex(
            model_name='host',
            index=models.Index(fields=['ip'], name='internet_ho_ip_756b5f_idx'),
        ),
        migrations.AddIndex(
            model_name='port',
            index=models.Index(fields=['port_number'], name='internet_po_port_nu_467b03_idx'),
        ),
        migrations.AddIndex(
            model_name='port',
            index=models.Index(fields=['proto'], name='internet_po_proto_cd209c_idx'),
        ),
    ]
