# Generated by Django 5.1.1 on 2025-09-08 06:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0003_add_banner_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerGrabJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher number = higher priority')),
                ('host_ip', models.CharField(max_length=255)),
                ('port_number', models.PositiveIntegerField()),
                ('protocol', models.CharField(default='tcp', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('banner', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assigned_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_grab_jobs', to='internet.jobworker')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_grab_jobs', to='internet.port')),
                ('scanner_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner_grab_jobs', to='internet.scannerjob')),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
                'indexes': [models.Index(fields=['status'], name='internet_ba_status_f852f6_idx'), models.Index(fields=['host_ip', 'port_number'], name='internet_ba_host_ip_937255_idx'), models.Index(fields=['assigned_worker'], name='internet_ba_assigne_c93e1c_idx'), models.Index(fields=['scanner_job'], name='internet_ba_scanner_562436_idx')],
            },
        ),
    ]
