# Generated by Django 5.1.1 on 2025-09-08 07:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0004_add_banner_grab_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='AncillaryJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('job_type', models.CharField(choices=[('banner_grab', 'Banner Grab'), ('domain_enum', 'Domain Enumeration'), ('ssl_cert', 'SSL Certificate'), ('service_detection', 'Service Detection'), ('vulnerability_scan', 'Vulnerability Scan')], default='banner_grab', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher number = higher priority')),
                ('host_ip', models.CharField(max_length=255)),
                ('port_number', models.PositiveIntegerField(blank=True, null=True)),
                ('protocol', models.CharField(default='tcp', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result_data', models.JSONField(blank=True, default=dict, help_text='Job-specific result data')),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assigned_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ancillary_jobs', to='internet.jobworker')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ancillary_jobs', to='internet.host')),
                ('port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ancillary_jobs', to='internet.port')),
                ('scanner_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ancillary_jobs', to='internet.scannerjob')),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.DeleteModel(
            name='BannerGrabJob',
        ),
        migrations.AddIndex(
            model_name='ancillaryjob',
            index=models.Index(fields=['status'], name='internet_an_status_dd8fc7_idx'),
        ),
        migrations.AddIndex(
            model_name='ancillaryjob',
            index=models.Index(fields=['job_type'], name='internet_an_job_typ_d90d16_idx'),
        ),
        migrations.AddIndex(
            model_name='ancillaryjob',
            index=models.Index(fields=['host_ip', 'port_number'], name='internet_an_host_ip_e80b0d_idx'),
        ),
        migrations.AddIndex(
            model_name='ancillaryjob',
            index=models.Index(fields=['assigned_worker'], name='internet_an_assigne_dc578b_idx'),
        ),
        migrations.AddIndex(
            model_name='ancillaryjob',
            index=models.Index(fields=['scanner_job'], name='internet_an_scanner_c58130_idx'),
        ),
    ]
