# Generated by Django 5.1.1 on 2025-08-27 00:22

import django.contrib.admin.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('internet', '0004_remove_port_internet_po_port_nu_0a01ab_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternetScannerDashboard',
            fields=[
            ],
            options={
                'verbose_name': 'Internet Scanner Dashboard',
                'verbose_name_plural': 'Internet Scanner Dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admin.logentry',),
            managers=[
                ('objects', django.contrib.admin.models.LogEntryManager()),
            ],
        ),
    ]
