# Generated by Django 5.1.1 on 2025-09-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0005_add_ancillary_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='asn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='country_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='geolocation_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='isp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='organization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='host',
            index=models.Index(fields=['country'], name='internet_ho_country_d456b9_idx'),
        ),
        migrations.AddIndex(
            model_name='host',
            index=models.Index(fields=['geolocation_updated'], name='internet_ho_geoloca_f1c412_idx'),
        ),
    ]
